apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-helm-chart-db.fullname" . }}
  labels:
{{ include "app-helm-chart-db.labels" . | indent 4 }}
spec:
  type: {{ .Values.spec.type }}
  ports:
    - port: 30081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "app-helm-chart-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
